### ISSUE TITLE
this is not transforming to lat long

### ISSUE THREAD

**Issue by tamarmot** [NeoGeographyToolkit/vipersci#19]
https://github.com/NeoGeographyToolkit/vipersci/blob/5cd805817120fe5e2b7863f2c4fed52dba13b7bf/src/vipersci/carto/heatmap.py#L419

**Comment by rbeyer** [comment]
If `get_gdal_info_from_rasterio()`'s second argument (`source_crs`) is `None` then the bounds information is just returned in whatever projection the provided data is in.  If a user of this function wants bounds in some other system (lonlat, for instance), then an appropriate CRS must be provided via the second argument.

That's how the function is currently constructed.  I see that it is only used in this library by `write_geotiff_rasterio()` which also has a `source_crs` argument that defaults to `None` that it passes on to this argument.

**Comment by tamarmot** [comment]
yep!
