### ISSUE TITLE
GitHub Action choking on GDAL

### ISSUE THREAD

**Issue by rbeyer** [NeoGeographyToolkit/vipersci#4]
The .github/worklfows/python-test.yml does not work.  Primarily because GDAL is a dependency, which can't just be pip-installed during test runs.

I suspect the answer might be to run a conda-install and then install python GDAL that way, but other things may need to be done.  Alternately, is GDAL itself really a dependency, or just historic (and anything that depends on `import gdal` is now really just doing `import rasterio` (although that may be a red herring if rasterio needs a libgdal installed anyway).

For the moment, the workflow has been manually disabled.

**Comment by otherorb** [comment]
At this stage, GDAL is not a dependency. We had talked about it being one for some of the higher level processing we were planning to do. My recommendation is that we remove that from the dependencies until and unless we actually do need it.

**Comment by rbeyer** [comment]
You're right, a grep of the codebase shows that we are never doing an `import gdal` but *rasterio* is definitely a dependency, and therefore any test system definitely needs a *libgdal* installed.  There is a way to do this with GitHub Actions, it'll just take some time to work it out.
